version: "3.9"
services:
  app:
    build: .
    ports:
      - "8067:8080"
    environment:
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=sa
      - DATABASE_NAME=hntoplinks
      - DATABASE_HOST=db
      - PORT=8080
    links:
      - db
  db:
    image: postgres:13.5
    ports:
     - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=sa
      - POSTGRES_USER=sa
      - POSTGRES_DB=hntoplinks

